name: container-deploy-CI

# For push event only when container project is changed
on:
  push:
    branches:
      - main
      - stage
    paths:
      - "packages/container/**"

# Change directory like how we do in terminal before starting any command.
defaults:
  run:
    working-directory: packages/container

# The jobs are mentioned here (In our case building the project to production version)
jobs:
  build:
    runs-on: ubuntu-latest
    # Series of steps to be done for a job
    steps:
      # Clone the repo so that job can access it.
      - uses: actions/checkout@v2
      - name: Installing all dependencies
        run: yarn
      - name: Building the project using prod config
        run: yarn build

      # Flip environment variable to true
      - name: Allowing unsecure commands
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      # AWS related action so that we can push the "dist" folder to S3
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Uploading dist folder to AWS S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Flip environment variable to true
      - name: Disabling unsecure commands
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=false' >> $GITHUB_ENV

      # Create invalidation entry for index.html to update the latest version with respect to javascript files
      - name: Creating invalidation entry for AWS Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
